Feature/0.1.0.beta.rro72 i/acceder a mis cursos
Roberto-Ruiz-Obregon-Tec/iOS-App pull request #38
Opened 2023-11-17 14:46 UTC by Ian326

2023-11-21 06:21 UTC, JosePeblo requested changes
Puedes hacer pull de dev y solucionar los merge conflicts?

2023-11-21 15:47 UTC, Ian326 commented
Ya pullee de dev :) resolví los conflicts.

2023-11-22 02:06 UTC, JosePeblo approved these changes

2023-11-23 00:03 UTC, ArmandoRosasB approved these changes

2023-11-23 03:05 UTC, merged